api_platform:
    defaults:
        route_prefix: '/'
    title: 'Benefitowo API'
    description: 'API for Benefitowo application with JWT authentication'
    version: '1.0.0'
    formats:
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
    error_formats:
        jsonproblem:
            mime_types:
                - application/problem+json
