api_platform:
    defaults:
        route_prefix: ''
    title: 'Benefitowo API'
    description: 'API for Benefitowo application with JWT authentication'
    version: '1.0.0'
    formats:
        json:
            mime_types:
                - application/json
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    error_formats:
        jsonproblem:
            mime_types:
                - application/problem+json
    use_symfony_listeners: true
