monolog:
    channels:
        - deprecation   # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - subdomain     # Channel for subdomain creation and management
        - app           # Channel for application-related logs

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!subdomain"]
            subdomain:
                type: stream
                path: "%kernel.logs_dir%/subdomain.log"
                level: info
                channels: ["subdomain"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
                channels: ["!subdomain"]

            nested:
                type: stream
                # stays within open_basedir
                path: "%kernel.project_dir%/var/logs/prod.log"
                level: debug
                formatter: monolog.formatter.json

            subdomain:
                type: stream
                # stays within open_basedir
                path: "%kernel.project_dir%/var/logs/subdomain.log"
                level: info
                channels: ["subdomain"]
                formatter: monolog.formatter.json

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: stream
                channels: [deprecation]
                # you can also switch this to "%kernel.logs_dir%/deprecations.log" if stderr isn't visible on your host
                path: "php://stderr"
                formatter: monolog.formatter.json