services:
  db:
    image: postgres:16-alpine
    container_name: apip-postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apip-php
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://app:app@db:5432/app?serverVersion=16&charset=utf8"
    volumes:
      - ./:/var/www/html:cached
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: apip-nginx
    depends_on:
      - php
    ports:
      - "8080:80"              # visit http://benefitowo.webdev:8080
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
