version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: apip-postgres
    environment:
      POSTGRES_DB: sbapp
      POSTGRES_USER: sbapp
      POSTGRES_PASSWORD: sbapp
    volumes:
      - sbapp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sbapp -d sbapp"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: apip-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apip-php
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://sbapp:sbapp@db:5432/sbapp?serverVersion=16&charset=utf8"
      REDIS_URL: "redis://redis:6379"
      APP_URL: "http://simplybooking.webdev:3000"
    volumes:
      - ./:/var/www/html:cached
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend

  apache:
    image: httpd:2.4-alpine
    container_name: apip-apache
    depends_on:
      - php
    ports:
      - "8080:80"                    # visit http://simplybooking.webdev:8080
    volumes:
      - ./:/var/www/html:ro
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - backend

volumes:
  sbapp:
  redisdata:

networks:
  backend:
    driver: bridge