oauth_google:
    path: /api/auth/google
    controller: App\Controller\OAuthController::googleOAuth
    methods: [GET]

oauth_google_callback:
    path: /api/auth/google/callback
    controller: App\Controller\OAuthController::googleOAuthCallback
    methods: [GET]