<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251016225130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('ALTER TABLE apps DROP CONSTRAINT fk_f5037c2ba76ed395');
        $this->addSql('ALTER TABLE apps ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE apps ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN apps.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN apps.updated_at IS \'\'');
        $this->addSql('ALTER TABLE apps ADD CONSTRAINT FK_101C7E5AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_5c4695f5989d9b62 RENAME TO UNIQ_101C7E5A989D9B62');
        $this->addSql('ALTER INDEX idx_f5037c2ba76ed395 RENAME TO IDX_101C7E5AA76ED395');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT fk_3af346687f2e88e7');
        $this->addSql('ALTER TABLE categories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE categories ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF346687987212D FOREIGN KEY (app_id) REFERENCES apps (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_3af346687f2e88e7 RENAME TO IDX_3AF346687987212D');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT fk_b3ba5a5a12469de2');
        $this->addSql('ALTER TABLE products ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE products ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE products ALTER product_stock DROP DEFAULT');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_1483a5e9f85e0677 RENAME TO UNIQ_1483A5E9AA08CB10');
        $this->addSql('ALTER INDEX idx_8f7c2c7ca76ed395 RENAME TO IDX_6A9D3293A76ED395');
        $this->addSql('ALTER INDEX idx_8f7c2c7c7987212c RENAME TO IDX_6A9D32937987212D');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE apps DROP CONSTRAINT FK_101C7E5AA76ED395');
        $this->addSql('ALTER TABLE apps ALTER id SET DEFAULT nextval(\'apps_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE apps ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN apps.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN apps.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE apps ADD CONSTRAINT fk_f5037c2ba76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_101c7e5aa76ed395 RENAME TO idx_f5037c2ba76ed395');
        $this->addSql('ALTER INDEX uniq_101c7e5a989d9b62 RENAME TO uniq_5c4695f5989d9b62');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF346687987212D');
        $this->addSql('ALTER TABLE categories ALTER id SET DEFAULT nextval(\'categories_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE categories ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT fk_3af346687f2e88e7 FOREIGN KEY (app_id) REFERENCES apps (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_3af346687987212d RENAME TO idx_3af346687f2e88e7');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A12469DE2');
        $this->addSql('ALTER TABLE products ALTER id SET DEFAULT nextval(\'products_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE products ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE products ALTER product_stock SET DEFAULT 0');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT fk_b3ba5a5a12469de2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_6a9d3293a76ed395 RENAME TO idx_8f7c2c7ca76ed395');
        $this->addSql('ALTER INDEX idx_6a9d32937987212d RENAME TO idx_8f7c2c7c7987212c');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users DROP email_verification_token');
        $this->addSql('ALTER TABLE users DROP email_verification_token_expires_at');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_1483a5e9aa08cb10 RENAME TO uniq_1483a5e9f85e0677');
    }
}
