<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251018110908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create orders table for storing checkout form data';
    }

    public function up(Schema $schema): void
    {
        // Create orders table
        $this->addSql('CREATE TABLE orders (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            firstname VARCHAR(255) NOT NULL,
            lastname VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL,
            shipping_location VARCHAR(50) NOT NULL,
            shipping_address TEXT DEFAULT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            user_id INT NOT NULL,
            app_id INT NOT NULL,
            PRIMARY KEY(id)
        )');
        
        // Create indexes for foreign keys
        $this->addSql('CREATE INDEX IDX_E52FFDEEA76ED395 ON orders (user_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE7987212D ON orders (app_id)');
        
        // Add foreign key constraints
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE7987212D FOREIGN KEY (app_id) REFERENCES apps (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // Drop foreign key constraints
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEEA76ED395');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE7987212D');
        
        // Drop indexes
        $this->addSql('DROP INDEX IDX_E52FFDEEA76ED395');
        $this->addSql('DROP INDEX IDX_E52FFDEE7987212D');
        
        // Drop orders table
        $this->addSql('DROP TABLE orders');
    }
}
