<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251018110908 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create orders table for storing checkout form data';
    }

    public function up(Schema $schema): void
    {
        // Create orders table only if it doesn't exist
        $this->addSql('DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = \'orders\') THEN
                CREATE TABLE orders (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    firstname VARCHAR(255) NOT NULL,
                    lastname VARCHAR(255) NOT NULL,
                    email VARCHAR(255) NOT NULL,
                    shipping_location VARCHAR(50) NOT NULL,
                    shipping_address TEXT DEFAULT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                    user_id INT NOT NULL,
                    app_id INT NOT NULL,
                    PRIMARY KEY(id)
                );
                
                -- Create indexes for foreign keys
                CREATE INDEX IDX_E52FFDEEA76ED395 ON orders (user_id);
                CREATE INDEX IDX_E52FFDEE7987212D ON orders (app_id);
                
                -- Add foreign key constraints
                ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
                ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE7987212D FOREIGN KEY (app_id) REFERENCES apps (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
            END IF;
        END $$;');
    }

    public function down(Schema $schema): void
    {
        // Drop orders table and related objects only if they exist
        $this->addSql('DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = \'orders\') THEN
                -- Drop foreign key constraints
                IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = \'FK_E52FFDEEA76ED395\') THEN
                    ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEEA76ED395;
                END IF;
                IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = \'FK_E52FFDEE7987212D\') THEN
                    ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE7987212D;
                END IF;
                
                -- Drop indexes
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = \'IDX_E52FFDEEA76ED395\') THEN
                    DROP INDEX IDX_E52FFDEEA76ED395;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = \'IDX_E52FFDEE7987212D\') THEN
                    DROP INDEX IDX_E52FFDEE7987212D;
                END IF;
                
                -- Drop orders table
                DROP TABLE orders;
            END IF;
        END $$;');
    }
}
