<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251018073417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE greeting_id_seq CASCADE');
        $this->addSql('ALTER TABLE apps ADD CONSTRAINT FK_101C7E5AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE budgets ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE budgets ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_7f13f14aa76ed395 RENAME TO IDX_DCAA9548A76ED395');
        $this->addSql('ALTER INDEX idx_7f13f14a7987212d RENAME TO IDX_DCAA95487987212D');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT fk_bef484451ad5cdbf');
        $this->addSql('ALTER TABLE cart_items ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE cart_items ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484451AD5CDBF FOREIGN KEY (cart_id) REFERENCES carts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT FK_BEF484454584665A FOREIGN KEY (product_id) REFERENCES products (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE carts ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE carts ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_4e004aac_a76ed395 RENAME TO IDX_4E004AACA76ED395');
        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF346687987212D FOREIGN KEY (app_id) REFERENCES apps (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE products ADD CONSTRAINT FK_B3BA5A5A12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B3BA5A5A12469DE2 ON products (category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE greeting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('ALTER TABLE apps DROP CONSTRAINT FK_101C7E5AA76ED395');
        $this->addSql('ALTER TABLE budgets ALTER id SET DEFAULT nextval(\'budgets_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE budgets ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_dcaa95487987212d RENAME TO idx_7f13f14a7987212d');
        $this->addSql('ALTER INDEX idx_dcaa9548a76ed395 RENAME TO idx_7f13f14aa76ed395');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484451AD5CDBF');
        $this->addSql('ALTER TABLE cart_items DROP CONSTRAINT FK_BEF484454584665A');
        $this->addSql('ALTER TABLE cart_items ALTER id SET DEFAULT nextval(\'cart_items_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE cart_items ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE cart_items ADD CONSTRAINT fk_bef484451ad5cdbf FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE carts ALTER id SET DEFAULT nextval(\'carts_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE carts ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_4e004aaca76ed395 RENAME TO idx_4e004aac_a76ed395');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF346687987212D');
        $this->addSql('ALTER TABLE products DROP CONSTRAINT FK_B3BA5A5A12469DE2');
        $this->addSql('DROP INDEX IDX_B3BA5A5A12469DE2');
    }
}
