controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api
    exclude: ['AuthController.php', 'OAuthController.php']

# Custom API Platform replacement controllers (without /api prefix)
custom_controllers:
    resource:
        path: ../src/CustomController/
        namespace: App\CustomController
    type: attribute
    prefix: ''
