controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api

# Auth controller with /api prefix
auth_controller:
    resource:
        path: ../src/AuthController/
        namespace: App\AuthController
    type: attribute
    prefix: /api

# Subdomain products controller (with /api prefix)
subdomain_products_controller:
    resource: App\ProductsController\SubdomainProductController
    type: attribute
    prefix: /api
